export default {
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",
  GET_REWARDS: "GET_REWARDS",
  GET_REWARDS_SUCCESS: "GET_REWARDS_SUCCESS",
  GET_REWARDS_FAIL: "GET_REWARDS_FAIL",
  PUT_REWARD: "PUT_REWARD",
  PUT_REWARD_SUCCESS: "PUT_REWARD_SUCCESS",
  PUT_REWARD_FAIL: "PUT_REWARD_FAIL",
};
